# Generated by Django 6.1.1 on 2026-09-12 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='condition',
            field=models.CharField(choices=[('M', 'Mint (Edicola)'), ('NM', 'Near Mint (Ottimo)'), ('FN', 'Fine (Buono)'), ('VG', 'Very Good (Discreto)'), ('GD', 'Good (Accettabile)')], default='NM', max_length=2, verbose_name='Stato di conservazione'),
        ),
        migrations.AddField(
            model_name='comic',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Venduto (Pezzo Unico)'),
        ),
        migrations.CreateModel(
            name='ComicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comics_details/%Y/%m/%d')),
                ('description', models.CharField(blank=True, help_text='Es. Fronte, Retro, Dettaglio strappo', max_length=200)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='shop.comic')),
            ],
        ),
    ]
